on:
    pull_request:
    push:
        branches:
        - main
        - pappenheimer_ci

jobs:
        format:
            name: Format
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                # Latest minor release of Python 3
                python-version: "3.x"
            - uses: pre-commit/action@v3.0.1

        tests:
            name: Run tests
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              - uses: prefix-dev/setup-pixi@v0.5.2
                with:
                  manifest-path: pyproject.toml
              - name: Run tests with pixi
                run: pixi run run_tests
